name: Update test CSV

on:
  workflow_dispatch: {}   # manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # allow pushing back to the repo

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show initial workspace
        run: |
          pwd
          ls -la
          git status

      - name: Ensure data directory exists
        run: |
          mkdir -p data
          ls -la

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run fetch script
        env:
          DFE_SOURCE_URL: https://people.sc.fsu.edu/~jburkardt/data/csv/hw_200.csv
          OUTPUT_DIR: data
          OUTPUT_NAME: dfe_attendance_latest.csv
        run: |
          python scripts/fetch_dfe.py
          echo "After running fetch:"
          ls -la
          ls -la data || true

      - name: Show git status before commit
        run: |
          git status
          git status --porcelain

      - name: Commit & push results (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          # Try commit; if nothing to commit, ignore the error
          git commit -m "Automated update: test CSV" || echo "Nothing to commit"
          git push || echo "Nothing to push"
