name: Update DfE Weekly CSV

on:
  schedule:
    # 06:00 UTC Monday–Friday (07:00 BST during summer)
    - cron: "0 6 * * 1-5"
  workflow_dispatch:
    inputs:
      required_columns_csv:
        description: "Comma-separated list of columns to keep (must ALL exist)"
        required: true
      rename_map_json:
        description: 'Optional JSON mapping of expected renames, e.g. {"Old Name":"New Name"}'
        required: false
      csv_delimiter:
        description: 'Optional delimiter (default ",")'
        required: false
      csv_encoding:
        description: 'Optional encoding (default "utf-8")'
        required: false
      output_path:
        description: 'Output path for filtered CSV'
        required: false
        default: 'data/dfe_weekly_attendance_latest.csv'

permissions:
  contents: write

concurrency:
  group: update-dfe-weekly
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas python-dateutil

      - name: Extract columns (strict)
        env:
          # Fixed weekly CSV source you provided
          SOURCE_URL: https://raw.githubusercontent.com/dfe-analytical-services/attendance-data-dashboard/refs/heads/main/data/EES_weekly_data.csv

          # Prefer typed input; fallback to repo secret if you want scheduled runs without manual input
          REQUIRED_COLUMNS_CSV: ${{ github.event.inputs.required_columns_csv || secrets.DFE_REQUIRED_COLUMNS_CSV }}

          # Optional niceties (can be blank)
          RENAME_MAP_JSON: ${{ github.event.inputs.rename_map_json || '' }}
          CSV_DELIMITER: ${{ github.event.inputs.csv_delimiter || ',' }}
          CSV_ENCODING: ${{ github.event.inputs.csv_encoding || 'utf-8' }}

          # Output path (input overrides default)
          OUTPUT_PATH: ${{ github.event.inputs.output_path || 'data/dfe_weekly_attendance_latest.csv' }}
        run: |
          python scripts/extract_columns_weekly.py

      - name: Commit changes (if any)
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "Update filtered DfE weekly CSV: $(date -u +'%Y-%m-%d %H:%M:%S')"
            git push
          else
            echo "No changes to commit."
          fi
